[build]
command = "yarn build --environment=staging"
environment = { NODE_VERSION = "12.22.1" }

[context.develop]
  environment = { NODE_VERSION = "12.22.1" }

[context.staging]
  environment = { NODE_VERSION = "12.22.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "12.22.1" }

[context.master]
  environment = { NODE_VERSION = "12.22.1" }
  command = "yarn build --environment=production"
